# Generated by Django 4.0 on 2022-01-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='header',
            new_name='name',
        ),
    ]
